import type { GameId, GameMeta, MiniGame } from "./types";
import { PulseClearanceGame } from "./pulse-clearance";
import { IonCircuitGame } from "./ion-circuit";
import { LatticeJumpGame } from "./lattice-jump";
import { NodeDefenseGame } from "./node-defense";
import { GravityVaultGame } from "./gravity-vault";
import { VoidDashGame } from "./void-dash";
import { CloudInterceptGame, FogKeyhuntGame, GalaxyStrafeGame, ShadowInfiltrateGame, StardustSweepGame } from "./pack-action";
import { ArcSliceGame, PhaseCrossingGame, PhotonBreakoutGame, PrismSnakeGame, StackMatrixGame } from "./pack-arcade";
import { CrescentShotGame, GyroLabyrinthGame, OrbitPuttGame, QuantumPoolGame, RingClashGame } from "./pack-sport";
import { ArcBatteryGame, CubeShoveGame, LatticeBlastGame, LightDuelGame, WormholeDiveGame } from "./pack-grid";

export const GAMES: GameMeta[] = [
  {
    id: "pulse-clearance",
    title: "脉冲清障",
    genre: "第一人称射击",
    blurb: "锁定准星，在霓虹回廊清掉一波波追踪体。掩体可挡，按住连射。五波之后撤离。",
    controls: "WASD 移动 · 鼠标瞄准 · 按住射击 · Shift 冲刺",
    touch: "fps",
    accent: "#22d3ee",
    fog: 0x070b14,
  },
  {
    id: "ion-circuit",
    title: "离子环道",
    genre: "第三人称竞速",
    blurb: "贴着离子管道漂移三圈。冲出赛道会掉速，错过检查点不算圈。",
    controls: "W / ↑ 加速 · S / ↓ 刹车 · A D 转向",
    touch: "steer",
    accent: "#818cf8",
    fog: 0x070816,
  },
  {
    id: "lattice-jump",
    title: "晶格跃迁",
    genre: "3D 平台跳跃",
    blurb: "在悬浮晶格上跳跃、蹭移动平台，集齐晶体后踏入传送门。",
    controls: "WASD 移动 · 空格跳跃",
    touch: "jump-move",
    accent: "#34d399",
    fog: 0x06110d,
  },
  {
    id: "node-defense",
    title: "节点防线",
    genre: "等距塔防",
    blurb: "把塔放在节点垫上，拦住沿链路推进的入侵体。守住五波。",
    controls: "点击空垫放置（40 能量）",
    touch: "none",
    accent: "#fbbf24",
    fog: 0x100c07,
  },
  {
    id: "gravity-vault",
    title: "重力密室",
    genre: "3D 机关解谜",
    blurb: "旋转重力，把自己摔到另一面墙上。三间密室，抵达绿光格即过关。",
    controls: "WASD 行走 · Q 绕竖轴转重力 · E 绕横轴转重力",
    touch: "gravity",
    accent: "#c084fc",
    fog: 0x0c0814,
  },
  {
    id: "void-dash",
    title: "虚空疾走",
    genre: "无尽跑酷",
    blurb: "自动向前冲。矮障要跳，高障要变道。速度会一直加。",
    controls: "A D 变道 · 空格跳跃",
    touch: "lanes",
    accent: "#22d3ee",
    fog: 0x050914,
  },
  {
    id: "stardust-sweep",
    title: "星尘扫荡",
    genre: "俯视双摇杆射击",
    blurb: "镜头在正上方。移动的同时朝鼠标方向开火，清掉 28 个星尘体。",
    controls: "WASD 移动 · 鼠标瞄准 · 点击 / 空格射击",
    touch: "dpad-fire",
    accent: "#22d3ee",
    fog: 0x071018,
  },
  {
    id: "fog-keyhunt",
    title: "雾廊寻钥",
    genre: "第一人称探索",
    blurb: "没有枪。在迷宫里取走全部钥匙，躲开巡游体，从出口撤离。",
    controls: "WASD 移动 · 鼠标转向",
    touch: "fps",
    accent: "#a78bfa",
    fog: 0x0b1018,
  },
  {
    id: "cloud-intercept",
    title: "云层截击",
    genre: "空战飞行",
    blurb: "驾驶机体在三维空间里转向，击落 12 个浮空靶。",
    controls: "A D 偏航 · W S 俯仰 · 空格 / 点击射击",
    touch: "steer",
    accent: "#818cf8",
    fog: 0x0a1224,
  },
  {
    id: "prism-snake",
    title: "棱镜蠕行",
    genre: "3D 贪吃蛇",
    blurb: "格子上生长。吃到 10 枚棱镜使身长到 12，撞墙或自噬即败。",
    controls: "WASD / 方向键转向",
    touch: "dpad",
    accent: "#34d399",
    fog: 0x081018,
  },
  {
    id: "photon-breakout",
    title: "光子弹幕",
    genre: "3D 打砖块",
    blurb: "挡板反弹光子，打掉整面砖墙。球出界扣命。",
    controls: "A D 移动挡板",
    touch: "paddle",
    accent: "#6366f1",
    fog: 0x0b1020,
  },
  {
    id: "orbit-putt",
    title: "轨道推杆",
    genre: "迷你高尔夫",
    blurb: "点击地面决定方向和力度，三洞完赛。球越远杆越重。",
    controls: "点击地面击球",
    touch: "none",
    accent: "#34d399",
    fog: 0x07140f,
  },
  {
    id: "quantum-pool",
    title: "量子撞球",
    genre: "台球物理",
    blurb: "白球是母球。把五颗彩球打进袋口，停稳后再击。",
    controls: "点击桌面给母球加力",
    touch: "none",
    accent: "#4ade80",
    fog: 0x07140c,
  },
  {
    id: "stack-matrix",
    title: "层积方阵",
    genre: "3D 俄罗斯方块",
    blurb: "方块落入井中。消掉 5 行过关，堆到顶失败。",
    controls: "A D 平移 · S 加速 · 空格 / Q 旋转",
    touch: "dpad-fire",
    accent: "#c084fc",
    fog: 0x0c0814,
  },
  {
    id: "shadow-infiltrate",
    title: "影隙潜入",
    genre: "潜行",
    blurb: "俯视潜入。待在守卫视野锥外，摸到绿色撤离垫。",
    controls: "WASD 移动",
    touch: "dpad",
    accent: "#c084fc",
    fog: 0x0a0c12,
  },
  {
    id: "arc-battery",
    title: "抛物炮台",
    genre: "弹道炮击",
    blurb: "调角度和力度，把炮弹打到对面堡垒上。12 发内夷平 4 座。",
    controls: "W S 角度 · A D 力度 · 空格开火",
    touch: "dpad-fire",
    accent: "#fb923c",
    fog: 0x140c08,
  },
  {
    id: "gyro-labyrinth",
    title: "陀螺迷宫",
    genre: "弹珠倾斜",
    blurb: "给球加速度，绕开黑洞，滚进绿色终点洞。",
    controls: "WASD 倾斜",
    touch: "dpad",
    accent: "#fbbf24",
    fog: 0x101018,
  },
  {
    id: "light-duel",
    title: "光轨对决",
    genre: "光轮竞速",
    blurb: "你和 AI 都会留下光轨。先撞墙或撞轨的人出局。",
    controls: "WASD 转向（不能 180° 掉头）",
    touch: "dpad",
    accent: "#22d3ee",
    fog: 0x050814,
  },
  {
    id: "lattice-blast",
    title: "晶格爆破",
    genre: "炸弹人",
    blurb: "格子地图上放炸弹。炸掉软墙，用爆炸波干掉 3 个敌人。",
    controls: "WASD 移动 · 空格放弹",
    touch: "dpad-fire",
    accent: "#f59e0b",
    fog: 0x0c1018,
  },
  {
    id: "cube-shove",
    title: "立方推移",
    genre: "推箱子",
    blurb: "把琥珀色箱子推到绿色目标格。三关。",
    controls: "WASD 推 / 走",
    touch: "dpad",
    accent: "#fbbf24",
    fog: 0x0c0818,
  },
  {
    id: "galaxy-strafe",
    title: "星河扫射",
    genre: "轨道射击",
    blurb: "机体自动向前。在轨道平面里平移并开火，击毁 20 个目标。",
    controls: "WASD 平移 · 空格 / 点击射击",
    touch: "dpad-fire",
    accent: "#a78bfa",
    fog: 0x050816,
  },
  {
    id: "ring-clash",
    title: "环心对撞",
    genre: "相扑",
    blurb: "在圆环上把对手撞下去。先赢两局。",
    controls: "WASD 冲撞",
    touch: "dpad",
    accent: "#f472b6",
    fog: 0x120814,
  },
  {
    id: "crescent-shot",
    title: "弦月试射",
    genre: "射箭",
    blurb: "点击屏幕决定箭矢方向。10 箭内射中 8 个靶环。",
    controls: "点击瞄准射出",
    touch: "none",
    accent: "#fb923c",
    fog: 0x140e08,
  },
  {
    id: "phase-crossing",
    title: "次元过街",
    genre: "格子过马路",
    blurb: "一次跳一格。躲开横向车流，跳到对岸。",
    controls: "WASD / 方向键 跳跃",
    touch: "dpad",
    accent: "#fb923c",
    fog: 0x0b1220,
  },
  {
    id: "wormhole-dive",
    title: "虫洞突穿",
    genre: "隧道飞行",
    blurb: "在管道里对准圆环飞。穿过 12 环，擦环三次即败。",
    controls: "WASD 平移",
    touch: "dpad",
    accent: "#c084fc",
    fog: 0x050816,
  },
  {
    id: "arc-slice",
    title: "弧光斩切",
    genre: "体感切割",
    blurb: "点击切开飞来的晶体。切开 16 个过关，切到炸弹或漏切三次失败。",
    controls: "点击切开",
    touch: "none",
    accent: "#fb7185",
    fog: 0x14080c,
  },
];

const FACTORIES: Record<GameId, () => MiniGame> = {
  "pulse-clearance": () => new PulseClearanceGame(),
  "ion-circuit": () => new IonCircuitGame(),
  "lattice-jump": () => new LatticeJumpGame(),
  "node-defense": () => new NodeDefenseGame(),
  "gravity-vault": () => new GravityVaultGame(),
  "void-dash": () => new VoidDashGame(),
  "stardust-sweep": () => new StardustSweepGame(),
  "fog-keyhunt": () => new FogKeyhuntGame(),
  "cloud-intercept": () => new CloudInterceptGame(),
  "prism-snake": () => new PrismSnakeGame(),
  "photon-breakout": () => new PhotonBreakoutGame(),
  "orbit-putt": () => new OrbitPuttGame(),
  "quantum-pool": () => new QuantumPoolGame(),
  "stack-matrix": () => new StackMatrixGame(),
  "shadow-infiltrate": () => new ShadowInfiltrateGame(),
  "arc-battery": () => new ArcBatteryGame(),
  "gyro-labyrinth": () => new GyroLabyrinthGame(),
  "light-duel": () => new LightDuelGame(),
  "lattice-blast": () => new LatticeBlastGame(),
  "cube-shove": () => new CubeShoveGame(),
  "galaxy-strafe": () => new GalaxyStrafeGame(),
  "ring-clash": () => new RingClashGame(),
  "crescent-shot": () => new CrescentShotGame(),
  "phase-crossing": () => new PhaseCrossingGame(),
  "wormhole-dive": () => new WormholeDiveGame(),
  "arc-slice": () => new ArcSliceGame(),
};

export function getGame(id: string): GameMeta | undefined {
  return GAMES.find((game) => game.id === id);
}

export function createGame(id: GameId): MiniGame {
  return FACTORIES[id]();
}
